FROM python:3.9.7
WORKDIR /app
COPY requirements/requirements.dev.txt ./
COPY requirements/requirements.common.txt ./
RUN pip install --no-cache-dir -r requirements.dev.txt
COPY . .

# ENTRYPOINT ["/bin/bash", "/app/startup.sh"]

# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]