
version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    # volumes:
      # - ./:/app
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=fastapi_test
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command:  uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi_test
    volumes:
      - postgres-d:/var/lib/postgresql/data

volumes:
  postgres-d: