version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=curas.postgres.database.azure.com
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=th!ere18E
      - DATABASE_NAME=curas
      - DATABASE_USERNAME=curas_admin@curas
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
