FROM python:3.10.2
LABEL org.opencontainers.image.source https://github.com/Sigularusrex/cura
WORKDIR /app
# copy dependencies
COPY pyproject.toml ./

ENV PYTHONPATH=${PYTHONPATH}:${PWD} 
RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]