# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - curatech

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b0f70a7dd0b743a2b55eaebd19b9e063 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4fa6abc7dfaf40cf9b3872e2318d2fab }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_b0f70a7dd0b743a2b55eaebd19b9e063 }}/sigularusrex/cura:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'curatech'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e0f27e688d564513889d094dfcd5a420 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_b0f70a7dd0b743a2b55eaebd19b9e063 }}/sigularusrex/cura:${{ github.sha }}'