name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  testing:

    runs-on: ubuntu-latest
    needs: [linting]

    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Building Docker Image and run the test
        run: bash scripts/test.sh
